### ISSUE TITLE
Add lines for new measures.

### ISSUE THREAD

**Issue by christophsax** [trendecon/dashboard#14]
I think the trendecon indicator looks interesting enough over the recent period. We probably should add new vertical lines for the new measures.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/1390827/103410658-8a133d80-4b6c-11eb-8e97-e54a1febeade.png">

**Comment by christophsax** [comment]
@benubah Have you previously worked on this? 

Either way, could you add a new line to all plots in the dashboard?

> Mandatory certificates, 13. September 2021

@vzei can review and may provide additional events to be added.

For other changes on the Website, Ben can cover for Angelica. Ben, you may also get in to contact with Angelica if you don't know how to proceed.

Thanks to all of you!

**Comment by benubah** [comment]
Thanks! Just to double check: are we adding the new line on all the charts here: https://www.trendecon.org/#home ?

**Comment by christophsax** [comment]
Correct. Ideally, we only have to specify it once, and it is applied to all charts.

**Comment by benubah** [comment]
Thanks! It's here: https://github.com/trendecon/dashboard/pull/18

**Comment by benubah** [comment]
Closed via https://github.com/trendecon/dashboard/pull/18
