### ISSUE TITLE
How to display the results for other countries?

### ISSUE THREAD

**Issue by karoliskoncevicius** [trendecon/dashboard#5]
What is the best way to display results for other countries?

I would like to start with `trendecon` index for Germany (DE), but later more will probably have to be included. Opening this issue for ideas about how to add it to the index.Rmd file.

**Comment by christophsax** [comment]
We have this data for a long time now. Should we add it to the website? How?

@vzei @izmartinez, in case you have an opinion.

**Comment by vzei** [comment]
I think we should add it to the website. Ideally, we have Switzerland and Germany in the same main figure but with the possibility to remove (untick) one or the other country. Would this be difficult to implement @karoliskoncevicius? Perhaps more efficient to discuss the options in a short call.

**Comment by christophsax** [comment]
Perhaps @angelicambg and @vzei? @karoliskoncevicius could do it as well but Angelica has more experience with the website.

**Comment by vzei** [comment]
@angelicambg do you want to call me later this or tomorrow afternoon regarding this?

**Comment by christophsax** [comment]
Seems to be done.
