### ISSUE TITLE
github action failed

### ISSUE THREAD

**Issue by angelicambg** [trendecon/dashboard#7]
Hi @pat-s, the github action failed only for the website (dashboard repo), so I updated manually. Could you take a look at this? Thanks a lot!

**Comment by christophsax** [comment]
Patrick is on vacations, so it may take a while.

@KKPMW perhaps you see what's wrong?

**Comment by karoliskoncevicius** [comment]
@christophsax looking at it now, but cannot promise anything yet.

**Comment by karoliskoncevicius** [comment]
@christophsax the error is related to ssh keys:

> git@github.com: Permission denied (publickey).

I noticed that @pat-s uploaded some new keys 3 days ago, so the problem is probably related to that.  
Not sure how to fix/restore.

**Comment by karoliskoncevicius** [comment]
In summary: trendecon/trendecon and trendecon/data have new deploy keys. But not trendecon/dashboard.

**Comment by karoliskoncevicius** [comment]
Seems like I am not allowed to view, copy, or change them

**Comment by pat-s** [comment]
Sorry for the inconvenience, I accidentally invalidated my public key (again) some days ago.

Anyone can resolve this in the future by calling `tic::use_ghactions_deploy()` from the repo root.
