### ISSUE TITLE
GitHub Actions is failing.

### ISSUE THREAD

**Issue by karoliskoncevicius** [trendecon/dashboard#9]
Need to figure out and fix the CI error:

     Quitting from lines 63-76 (index.Rmd)
     Error in validateCssUnit(sizeInfo$width) :
       CSS units must be a single-element numeric or character vector

**Comment by karoliskoncevicius** [comment]
The problem was tracked down to the changes in the `knitr` package:

1. `knitr` was last updated 4 days ago, just around the time the "tic" started failing.
2. When I downgraded the knitr package to version 1.29 everything started working again.

**Comment by karoliskoncevicius** [comment]
In the meantime - maybe we can add a temporary fix by requesting knitr version 1.29 on the server?
Not sure if this is possible to do with `tic`.

@pat-s @christophsax

**Comment by karoliskoncevicius** [comment]
Traced the bug further to this particular change in knitr:

https://github.com/yihui/knitr/pull/1877/files

**Comment by karoliskoncevicius** [comment]
Submitted a bug report in knitr: https://github.com/yihui/knitr/issues/1901

**Comment by pat-s** [comment]
Everything can be done with tic. I'd appreciate if you could read the documentation first how to do it.

If you cannot figure it out, I should update the documentation 🙂

**Comment by karoliskoncevicius** [comment]
@pat-s fair enough, I assumed you were the person maintaining the tic side of this project.

Issued a pull request, can you take a look if everything looks right to you ?

**Comment by pat-s** [comment]
tic is just a tool  to simplify things - it would be great if not just one person knows how to use/fix it 🙂
It should be possible for anyone to fix CI issues like that without having to refer to tic - at least this is my vision 😅

I can take a look in a few days if it still persists until then, I am currently taking some days off.
